const IPC_CONST = {
  WINDOW_CLOSE: 'WINDOW_CLOSE',
  WINDOW_MIN: 'WINDOW_MIN',
  WINDOW_FULL_SCREEN: 'WINDOW_FULL_SCREEN',
  WINDOW_MAXIMIZE: 'WINDOW_MAXIMIZE',
  DB_PERSON_INSERT: 'DB_PERSON_INSERT',
  DB_PERSON_INSERT_LIST: 'DB_PERSON_INSERT_LIST',
  DB_PERSON_UPDATE: 'DB_PERSON_UPDATE',
  DB_PERSON_DELETE_BY_ID: 'DB_PERSON_DELETE_BY_ID',
  DB_PERSON_QUERY_BY_ID: 'DB_PERSON_QUERY_BY_ID',
  DB_PERSON_QUERY_ALL: 'DB_PERSON_QUERY_ALL',
};
export default IPC_CONST;
